import Head from 'next/head'
import Banner from "@/components/Banner";
import Stages from "@/components/Stages";
import About from "@/components/About";
import Service from "@/components/Service";
import Profit from "@/components/Profit";
import Footer from "@/components/Footer";



export default function Home() {
  return (
    <>
      <Head>
        <title>Improvement Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.cdnfonts.com/css/along-sans-s2" rel="stylesheet"/>
        <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'/>
        <link href='https://fonts.googleapis.com/css?family=Ranchers' rel='stylesheet'/>
        <link href='https://fonts.googleapis.com/css?family=Questrial' rel='stylesheet'/>
        <link href='https://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <Stages/>
        <About/>
        <Service/>
        <Profit/>
        <Footer/>
      </main>
    </>
  )
}
